# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

triangular_index <- function(r, c) {
    .Call(`_motifmw_triangular_index`, r, c)
}

mw_cove_terra <- function(x, raster_window, directions, classes, ordered, normalization, ni, nw) {
    .Call(`_motifmw_mw_cove_terra`, x, raster_window, directions, classes, ordered, normalization, ni, nw)
}

